modLoader="javafml"

loaderVersion="${loader_version_range}"

license="${mod_license}"

[[mods]]

modId="${mod_id}"

version="${mod_version}"


displayName="${mod_name}"

authors="jmcmoon"

description='''
Compatibility patches for Immersive Portals.
'''

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neo_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="immersive_portals_core"
    type="required"
    versionRange="${immptl_version}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="ae2"
    type="optional"
    versionRange="${ae2_version}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="mekanism"
    type="optional"
    versionRange="${minecraft_version}-${mekanism_version}"
    ordering="AFTER"
    side="BOTH"

[[mixins]]
config="${mod_id}.ae2.mixins.json"
required_mods=["ae2", "immersive_portals_core"]

[[mixins]]
config="${mod_id}.mekanism.mixins.json"
required_mods=["mekanism", "immersive_portals_core"]
