name: Automatic Versioning

on:
  push:
    branches:
      - main
      - master

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.convver-version.outputs.tag }}
      prevTag: ${{ steps.convver-current.outputs.tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set Credentials
        run: |
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - run: npm set "//npm.pkg.github.com/:_authToken" ${{ secrets.GITHUB_TOKEN }}

      - name: Install Convver
        run: |
          npm install -g @jmcmahon1999/convver --@jmcmahon1999:registry=https://npm.pkg.github.com/
          npm install -g @jmcmahon1999/convver-gradle --@jmcmahon1999:registry=https://npm.pkg.github.com/

      - name: Convver Current
        id: convver-current
        run: echo "tag=$( convver current)" >> $GITHUB_OUTPUT

      - name: Convver Update
        id: convver-update
        run: convver update gradle -q

      - name: Get New Version
        id: convver-version
        run: echo "tag=$( convver current)" >> $GITHUB_OUTPUT

      - name: Push Changes
        if: ${{ steps.convver-version.outputs.tag != steps.convver-current.outputs.tag }}
        run: git push --follow-tags

      - name: Setup JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Make Gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Archive Built Wheels
        id: archive-wheel
        uses: actions/upload-artifact@v5
        with:
          name: build-$TAG
          path: ./build/libs/*

  release:
    needs: [ version ]
    runs-on: ubuntu-latest
    if: ${{ needs.version.outputs.tag != needs.version.outputs.prevTag }}
    env:
      TAG: ${{ needs.version.outputs.tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Download Artifacts
        uses: actions/download-artifact@v7
        with:
          name: build-$TAG
          path: ./build/libs
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${TAG/#/v} \
            './build/libs/*.jar' \
            --repo="$GITHUB_REPOSITORY" \
            --title="${TAG#v}" \
            --generate-notes \
            --fail-on-no-commits \
            --verify-tag